from django.db import models
from accounts.models import PatientUser


class enregistrementsInformations(models.Model):
    
    date_creation_enregistrement = models.DateTimeField(auto_now_add=True)
    date_derniere_modification_enregistrement = models.DateTimeField(auto_now=False)
    poids = models.DecimalField(max_digits=5, decimal_places=2)
    frequence_cardiaque_par_minute = models.IntegerField()
    tension_arterielle_systolique_prise_matin = models.IntegerField()
    tension_arterielle_systolique_prise_soir = models.IntegerField()
    tension_arterielle_diastolique_prise_matin = models.IntegerField()
    tension_arterielle_diastolique_prise_soir = models.IntegerField()
    tour_de_taille_en_centimetre = models.DecimalField(max_digits=5, decimal_places=2)
    medicaments_nombre_par_jour = models.DecimalField(max_digits=5, decimal_places=2)
    medicaments_oublie_matin = models.CharField(max_length=45)
    medicaments_oublie_soir = models.CharField(max_length=45)
    medicaments_symptomes_particuliers = models.CharField(max_length=200)
    medicaments_oublie_raison = models.CharField(max_length=200)
    medicaments_effet_secondaire_description = models.CharField(max_length=200)
    symptomes_cardio_vasculaires = models.CharField(max_length=200)
    dyspnee = models.CharField(max_length=45)
    palpitations_presence = models.CharField(max_length=45)
    palpitations_duree = models.IntegerField()
    palpitations_horaire = models.DateTimeField(auto_now_add=True)
    douleur_thoracique_presence = models.CharField(max_length=45)
    douleur_thoracique_duree = models.IntegerField()
    douleur_thoracique_horaire = models.DateTimeField(auto_now_add=True)
    malaise_presence = models.CharField(max_length=45)
    malaise_duree = models.IntegerField()
    malaise_horaire = models.DateTimeField(auto_now_add=True)
    oedeme_presence = models.CharField(max_length=45)
    activite_physique_presence = models.CharField(max_length=45)
    activite_physique_nature = models.CharField(max_length=200)
    activite_physique_duree = models.IntegerField()
    activite_physique_frequence = models.IntegerField()
    alimentation_nombre_repas_par_jour = models.IntegerField()
    alimentation_grignotage_presence = models.CharField(max_length=45)
    alimentation_type_grignotage = models.CharField(max_length=200)
    alimentation_quantite_eau = models.DecimalField(max_digits=5, decimal_places=2)
    alimentation_alcool_consommation = models.DecimalField(max_digits=5, decimal_places=2)
    alimentation_type_alcool = models.CharField(max_length=200)
    alimentation_nombre_de_verre = models.DecimalField(max_digits=5, decimal_places=2)
    episode_infectieux_presence = models.CharField(max_length=200)
    fievre_presence = models.CharField(max_length=45)
    natremie = models.DecimalField(max_digits=5, decimal_places=2)
    potassium = models.DecimalField(max_digits=5, decimal_places=2)
    creatinine = models.DecimalField(max_digits=5, decimal_places=2)
    clairance_de_la_creatinine_mdrd = models.DecimalField(max_digits=5, decimal_places=2)
    ntprobnp = models.DecimalField(max_digits=5, decimal_places=2)
    fer_serique = models.DecimalField(max_digits=5, decimal_places=2)
    taux_hemoglobine = models.DecimalField(max_digits=5, decimal_places=2)
    vs = models.DecimalField(max_digits=5, decimal_places=2)
    crp = models.DecimalField(max_digits=5, decimal_places=2)
    troponine = models.DecimalField(max_digits=5, decimal_places=2)
    taux_vitamine_d = models.DecimalField(max_digits=5, decimal_places=2)
    taux_acide_urique = models.DecimalField(max_digits=5, decimal_places=2)
    inr = models.DecimalField(max_digits=5, decimal_places=2)
    nombre_heure_devant_ecran = models.DecimalField(max_digits=5, decimal_places=2)
    nombre_heure_sommeil = models.DecimalField(max_digits=5, decimal_places=2)
    patients_id = models.ForeignKey(PatientUser, on_delete=models.CASCADE)