# Generated by Django 3.1.2 on 2020-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201030_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
